spring:

  servlet:
    multipart:
      max-file-size: 1GB
      max-request-size: 1GB

  application:
    name: resource-server



  datasource:
    url: jdbc:mysql://localhost:3306/ebook
    username: root
    password: At@170234

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/file-manager
  jpa:
    hibernate:
      ddl-auto: update

logging:
  level:
    org.springframework.security: debug



server:
  port: 9000

location:
  image: C:\\Users\\MinhNV\\Documents\\Do_an\\demo\\image
  content: C:\\Users\\MinhNV\\Documents\\Do_an\\demo\\content

